[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vehicle_factory = "pPYAk8suZZd8xqyVs49rugZztvfV7a8E7AJuvmQHRLf"

[programs.devnet]
vehicle_factory = "pPYAk8suZZd8xqyVs49rugZztvfV7a8E7AJuvmQHRLf"

[programs.testnet]
vehicle_factory = "pPYAk8suZZd8xqyVs49rugZztvfV7a8E7AJuvmQHRLf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/huynb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
