[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vehicle_factory = "95w6ZbaNJV2sJzDuQQxE3wqshfyE3Y1Q3PHJWDdMCHWF"
vehicle = "9AnzrXaEB7xpbrAJFbaxc6ztM8uQvwg4puKqBoL77fma"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/huynb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
