[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vehicle_factory = "7W48nzpFQ1t4fXg7AKwDPouFaAkByF7oKfGDsuH5wTaD"

[programs.devnet]
vehicle_factory = "7W48nzpFQ1t4fXg7AKwDPouFaAkByF7oKfGDsuH5wTaD"

[programs.testnet]
vehicle_factory = "7W48nzpFQ1t4fXg7AKwDPouFaAkByF7oKfGDsuH5wTaD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/huynb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
