[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_car_auction_dapp = "vBHFCJFKn5oM48KxE9oEzxCQMLTjhbC3USMeY4SzhcG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/huynb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
