[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vehicle_factory = "9NfoQ6i5WqJEsD3HhJ9GonKRtvjREV8yER5DXTnp2w95"

[programs.devnet]
vehicle_factory = "9NfoQ6i5WqJEsD3HhJ9GonKRtvjREV8yER5DXTnp2w95"

[programs.testnet]
vehicle_factory = "9NfoQ6i5WqJEsD3HhJ9GonKRtvjREV8yER5DXTnp2w95"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/huynb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
